# list of all app paths
spotify = "/Applications/spotify.app"
discord = "/Applications/discord.app"
spark = "/Applications/spark.app"
adobe_illustrator = "/Applications/Adobe\ Illustrator\ 2022.app"
adobe_photoshop = "/Applications/Adobe\ Photoshop\ 2022/Adobe\ Photoshop\ 2022.app"
adobe_premiere = "/Applications/Adobe\ Premiere\ Pro\ 2022/Adobe\ Premiere\ Pro\ 2022.app"
brave = "/Applications/Brave Browser.app/"
excel = "/Applications/Microsoft\ Excel.app/"
onenote = "/Applications/Microsoft\ OneNote.app/"
powerpoint = "/Applications/Microsoft\ PowerPoint.app/"
word = "/Applications/Microsoft\ Word.app/"
outlook = "/Applications/Microsoft\ Outlook.app/"
teams = "/Applications/Microsoft\ Teams.app/"
whatsapp = "/Applications/WhatsApp.app/"
proton_vpn = "/Applications/ProtonVPN.app/"
notion = "/Applications/Notion.app/"
ccleaner = "/Applications/Ccleaner.app/"
qbittorent = "/Applications/qBittorrent.app/"

