# list of all the websites
youtube = "https://youtube.com"
habsnet = "https://habsnet.habsboys.org.uk/Pages/PupilPortal.aspx"
outlook = "https://outlook.office365.com/mail/inbox"
smhw = "https://www.satchelone.com/todos/issued"
amazon = "https://amazon.co.uk"
ebay = "https://ebay.co.uk"
gmail = "https://gmail.com"
bbc_bitesize = "https://www.bbc.co.uk/bitesize"
google = "https://www.google.com"
github = "https://github.com"
google_drive = "https://drive.google.com"
imdb = "https://imdb.com"
reddit = "https://reddit.com"
netflix = "https://netflix.com"
wikipedia = "https://wikipedia.org"
